"""
Authentication Router
──────────────────────
Routes:
  POST /auth/signup                  Register a new admin (or legacy employee)
  POST /auth/login                   Authenticate → receive JWT
  POST /auth/join                    Employee self-registers using a join code → pending
  POST /auth/admin/create-employee   Admin creates an employee directly → active
  GET  /auth/admin/pending           Admin lists pending employee requests
  POST /auth/admin/approve/{user_id} Admin approves a pending employee
  POST /auth/admin/reject/{user_id}  Admin rejects a pending employee
  GET  /auth/admin/join-code         Admin retrieves their org's join code
"""
from fastapi import APIRouter, Depends, HTTPException, Request, status
from sqlalchemy.orm import Session

from app.database import get_db
from app.models.user import User, UserRole, UserStatus
from app.models.org_db_config import OrgDbConfig
from app.schemas.auth import (
    SignupRequest, SignupResponse,
    LoginRequest, LoginResponse,
    JoinRequest, JoinResponse,
    PendingEmployeeOut,
)
from app.core.security import hash_password, verify_password, create_access_token
from app.core.deps import require_role, get_current_user
from app.core.audit import log_action

router = APIRouter()

_admin_dep = require_role(UserRole.admin)


# ── POST /auth/signup ──────────────────────────────────────────────────────────
@router.post("/signup", response_model=SignupResponse, status_code=status.HTTP_201_CREATED)
def signup(payload: SignupRequest, request: Request, db: Session = Depends(get_db)):
    """Register a new admin account. Admin signup creates an OrgDbConfig stub."""
    if db.query(User).filter(User.email == payload.email).first():
        raise HTTPException(status_code=400, detail="An account with this email already exists.")

    user = User(
        name=payload.name,
        email=payload.email,
        hashed_password=hash_password(payload.password),
        role=UserRole.admin,
        status=UserStatus.active,
    )
    db.add(user)
    db.flush()
    user.org_id = user.id

    org_name = payload.organization_name or f"{payload.name}'s Organization"
    org_stub = OrgDbConfig(
        org_id=user.id,
        organization_name=org_name,
        db_type="postgresql",
        connection_status="disconnected",
        # join_code auto-generated by model default
    )
    db.add(org_stub)
    db.commit()
    db.refresh(user)

    log_action(db, "USER_SIGNUP", org_id=user.org_id, user_id=user.id,
               detail=f"Admin signup: {user.email}", request=request)

    token = create_access_token({"sub": str(user.id), "role": user.role, "org_id": str(user.org_id)})
    return SignupResponse(access_token=token, role=user.role)


# ── POST /auth/login ───────────────────────────────────────────────────────────
@router.post("/login", response_model=LoginResponse)
def login(payload: LoginRequest, request: Request, db: Session = Depends(get_db)):
    """Authenticate and return a JWT."""
    user = db.query(User).filter(User.email == payload.email).first()
    if not user or not verify_password(payload.password, user.hashed_password):
        raise HTTPException(status_code=401, detail="Invalid email or password.")

    if user.status == UserStatus.pending:
        raise HTTPException(
            status_code=403,
            detail="Your account is pending admin approval. Please wait for your admin to approve your request.",
        )
    if user.status == UserStatus.rejected:
        raise HTTPException(
            status_code=403,
            detail="Your account request was rejected. Please contact your organisation admin.",
        )

    log_action(db, "USER_LOGIN", org_id=user.org_id, user_id=user.id,
               detail=f"Login: {user.email}", request=request)

    token = create_access_token({"sub": str(user.id), "role": user.role, "org_id": str(user.org_id)})
    return LoginResponse(access_token=token, role=user.role)


# ── POST /auth/join ────────────────────────────────────────────────────────────
@router.post("/join", response_model=JoinResponse, status_code=status.HTTP_201_CREATED)
def join_with_code(payload: JoinRequest, request: Request, db: Session = Depends(get_db)):
    """
    Employee self-registers using the organisation's join code.
    Account starts as PENDING — admin must approve before the employee can log in.
    """
    # Find the org by join code
    org = db.query(OrgDbConfig).filter(OrgDbConfig.join_code == payload.join_code.upper()).first()
    if not org:
        raise HTTPException(status_code=404, detail="Invalid join code. Please check with your admin.")

    # Check for duplicate email
    if db.query(User).filter(User.email == payload.email).first():
        raise HTTPException(status_code=400, detail="An account with this email already exists.")

    employee = User(
        name=payload.name,
        email=payload.email,
        hashed_password=hash_password(payload.password),
        role=UserRole.employee,
        status=UserStatus.pending,   # ← pending until approved
        org_id=org.org_id,
    )
    db.add(employee)
    db.commit()
    db.refresh(employee)

    log_action(db, "EMPLOYEE_JOINED", org_id=org.org_id, user_id=employee.id,
               detail=f"Employee join request: {employee.email}", request=request)

    return JoinResponse(
        message="Your account request has been submitted. You will be notified once your admin approves it.",
        email=employee.email,
    )


# ── POST /auth/admin/create-employee ──────────────────────────────────────────
@router.post("/admin/create-employee", response_model=SignupResponse, status_code=201)
def create_employee(
    payload: SignupRequest,
    request: Request,
    db: Session = Depends(get_db),
    current_user: User = Depends(_admin_dep),
):
    """Admin creates an employee directly — account is immediately active."""
    if db.query(User).filter(User.email == payload.email).first():
        raise HTTPException(status_code=400, detail="An account with this email already exists.")

    employee = User(
        name=payload.name,
        email=payload.email,
        hashed_password=hash_password(payload.password),
        role=UserRole.employee,
        status=UserStatus.active,     # ← directly active
        org_id=current_user.org_id,
    )
    db.add(employee)
    db.commit()
    db.refresh(employee)

    log_action(db, "EMPLOYEE_CREATED", org_id=current_user.org_id, user_id=current_user.id,
               detail=f"Admin created employee: {employee.email}", request=request)

    token = create_access_token({"sub": str(employee.id), "role": employee.role, "org_id": str(employee.org_id)})
    return SignupResponse(access_token=token, role=employee.role)


# ── GET /auth/admin/pending ────────────────────────────────────────────────────
@router.get("/admin/pending", response_model=list[PendingEmployeeOut])
def list_pending_employees(
    db: Session = Depends(get_db),
    current_user: User = Depends(_admin_dep),
):
    """Admin: list all employees waiting for approval in this org."""
    pending = (
        db.query(User)
        .filter(
            User.org_id == current_user.org_id,
            User.status == UserStatus.pending,
            User.role == UserRole.employee,
        )
        .order_by(User.created_at)
        .all()
    )
    return pending


# ── POST /auth/admin/approve/{user_id} ────────────────────────────────────────
@router.post("/admin/approve/{user_id}", status_code=200)
def approve_employee(
    user_id: str,
    request: Request,
    db: Session = Depends(get_db),
    current_user: User = Depends(_admin_dep),
):
    """Admin: approve a pending employee. They can now log in."""
    employee = _get_org_employee(user_id, current_user, db)
    if employee.status != UserStatus.pending:
        raise HTTPException(status_code=400, detail="Employee is not in pending state.")

    employee.status = UserStatus.active
    db.commit()

    log_action(db, "EMPLOYEE_APPROVED", org_id=current_user.org_id, user_id=current_user.id,
               detail=f"Approved employee: {employee.email}", request=request)

    return {"message": f"{employee.name} ({employee.email}) has been approved and can now log in."}


# ── POST /auth/admin/reject/{user_id} ─────────────────────────────────────────
@router.post("/admin/reject/{user_id}", status_code=200)
def reject_employee(
    user_id: str,
    request: Request,
    db: Session = Depends(get_db),
    current_user: User = Depends(_admin_dep),
):
    """Admin: reject a pending employee."""
    employee = _get_org_employee(user_id, current_user, db)
    if employee.status != UserStatus.pending:
        raise HTTPException(status_code=400, detail="Employee is not in pending state.")

    employee.status = UserStatus.rejected
    db.commit()

    log_action(db, "EMPLOYEE_REJECTED", org_id=current_user.org_id, user_id=current_user.id,
               detail=f"Rejected employee: {employee.email}", request=request)

    return {"message": f"{employee.name} has been rejected."}


# ── GET /auth/admin/join-code ──────────────────────────────────────────────────
@router.get("/admin/join-code")
def get_join_code(
    db: Session = Depends(get_db),
    current_user: User = Depends(_admin_dep),
):
    """Admin: retrieve the organisation's join code to share with employees."""
    org = db.query(OrgDbConfig).filter(OrgDbConfig.org_id == current_user.org_id).first()
    if not org:
        raise HTTPException(status_code=404, detail="Organisation config not found.")
    return {
        "join_code": org.join_code,
        "organization_name": org.organization_name,
        "message": "Share this code with employees so they can self-register.",
    }


# ── GET /auth/me ────────────────────────────────────────────────────────────────
@router.get("/me")
def get_my_profile(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Return the currently authenticated user's full profile."""
    org_cfg = db.query(OrgDbConfig).filter(OrgDbConfig.org_id == current_user.org_id).first()
    return {
        "id":                str(current_user.id),
        "name":              current_user.name,
        "email":             current_user.email,
        "role":              current_user.role,
        "status":            current_user.status,
        "org_id":            str(current_user.org_id) if current_user.org_id else None,
        "organization_name": org_cfg.organization_name if org_cfg else "SQLense Org",
        "created_at":        current_user.created_at.isoformat() if current_user.created_at else None,
    }



# ── PUT /auth/me ─────────────────────────────────────────────────────────────
from pydantic import BaseModel as _PydanticBase

class UpdateProfileRequest(_PydanticBase):
    name:             str | None = None
    current_password: str | None = None
    new_password:     str | None = None


@router.put("/me")
def update_my_profile(
    payload: UpdateProfileRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Update the currently authenticated user's name and/or password."""
    if payload.name and payload.name.strip():
        current_user.name = payload.name.strip()

    if payload.new_password:
        if not payload.current_password:
            raise HTTPException(status_code=400, detail="Current password is required to set a new password.")
        if not verify_password(payload.current_password, current_user.hashed_password):
            raise HTTPException(status_code=400, detail="Current password is incorrect.")
        if len(payload.new_password) < 8:
            raise HTTPException(status_code=400, detail="New password must be at least 8 characters.")
        current_user.hashed_password = hash_password(payload.new_password)

    db.commit()
    db.refresh(current_user)
    return {
        "id":    str(current_user.id),
        "name":  current_user.name,
        "email": current_user.email,
        "role":  current_user.role,
    }


# ── Helper ─────────────────────────────────────────────────────────────────────
def _get_org_employee(user_id: str, current_admin: User, db: Session) -> User:
    """Fetch an employee and verify they belong to the admin's org."""
    employee = db.query(User).filter(User.id == user_id).first()
    if not employee:
        raise HTTPException(status_code=404, detail="User not found.")
    if employee.org_id != current_admin.org_id:
        raise HTTPException(status_code=403, detail="This user does not belong to your organisation.")
    return employee

